# Generated by Django 3.1.1 on 2020-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol', models.CharField(max_length=64)),
                ('illust', models.CharField(max_length=128)),
                ('vocal', models.IntegerField()),
                ('dance', models.IntegerField()),
                ('visual', models.IntegerField()),
            ],
        ),
    ]
