# Generated by Django 3.1.1 on 2020-09-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utahime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idol',
            new_name='S_Idol',
        ),
    ]
